# reference: https://blitzjs.com/docs/postgres
# docker-compose up -d service-name

version: "3.7"

services:

  postgres:
    image: postgres:latest
    volumes:
      - postgresData:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ncf
      - POSTGRES_PASSWORD=ncf2022
      - POSTGRES_DB=postgres
      - DATABASE_URL=postgresql://ncf:ncf2022@localhost:5432/postgres
    ports:
      - 5432:5432

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=ncf
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - mysqlData:/var/lib/mysql

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - mongoData:/data/db

  # docker run -d --name elasticsearch --net somenetwork -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:tag
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearchData:/usr/share/elasticsearch/data
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redisData:/data

  # 4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, 15671/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp
  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
      - 15691:15691
      - 15692:15692
      - 25672:25672
    volumes:
      - rabbitmqData:/var/lib/rabbitmq

volumes:
  postgresData:
  mysqlData:
  mongoData:
  elasticsearchData:
  redisData:
  rabbitmqData:
