# reference: https://blitzjs.com/docs/postgres
# docker-compose up -d service-name

version: "3.7"

services:

  postgres:
    image: postgres:latest
    volumes:
      - postgresData:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ncf
      - POSTGRES_PASSWORD=ncf2022
      - POSTGRES_DB=postgres
      - DATABASE_URL=postgresql://ncf:ncf2022@localhost:5432/postgres
    ports:
      - 5432:5432

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=ncf
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - mysqlData:/var/lib/mysql

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - mongoData:/data/db

  # docker run -d --name elasticsearch --net somenetwork -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:tag
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearchData:/usr/share/elasticsearch/data

  # docker run -d --name kibana --net somenetwork -p 5601:5601 kibana:tag
  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.2
    ports:
      - 5601:5601

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redisData:/data

  # https://hub.docker.com/_/rethinkdb
  # http://localhost:28080/ 控制台
  rethinkdb:
    image: rethinkdb:2.4.2
    ports:
      - 28015:28015
      - 29015:29015
      - 28080:8080
    volumes:
      - rethinkData:/data

  # 4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, 15671/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp
  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
      - 15691:15691
      - 15692:15692
      - 25672:25672
    volumes:
      - rabbitmqData:/var/lib/rabbitmq

  # https://hub.docker.com/r/bitnami/kafka
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - 9092:9092
      - 9093:9093
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_HEAP_OPTS=-Xmx512m -Xms512m
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  # https://hub.docker.com/r/yugabytedb/yugabyte
  # https://www.yugabyte.com

  # https://nats.io
  # https://hub.docker.com/_/nats
  nats:
    image: docker.io/nats:2.8.4-alpine3.15
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222

volumes:
  postgresData:
  mysqlData:
  mongoData:
  elasticsearchData:
  redisData:
  rethinkData:
  rabbitmqData:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
