# reference: https://blitzjs.com/docs/postgres
# docker-compose up -d

version: "3.7"

services:
  db:
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    env_file: ./.env.local #Here we are using the already existing .env.local file
    ports:
      - 5432:5432

  db-test:
    image: postgres:latest
    env_file: ./.env.test.local
    ports:
      - 5433:5432

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=ncf
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - mysqlData:/var/lib/mysql

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - mongoData:/data/db
volumes:
  data:
  mysqlData:
  mongoData:
