# reference: https://blitzjs.com/docs/postgres
# docker-compose up -d

version: "3.7"

services:

  postgres:
    image: postgres:latest
    volumes:
      - postgresData:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ncf
      - POSTGRES_PASSWORD=ncf2022
      - POSTGRES_DB=postgres
      - DATABASE_URL=postgresql://ncf:ncf2022@localhost:5432/postgres
    ports:
      - 5432:5432

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=ncf
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - mysqlData:/var/lib/mysql

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - mongoData:/data/db

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redisData:/data

volumes:
  postgresData:
  mysqlData:
  mongoData:
  redisData:
